---
ID: "d2852a39-6e1d-4db9-902d-78065109afc6"
Parent: "b1118780-e024-4732-b69b-4e6f5c954537"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/industry-verticals/littelfuse/Presentation/Headless Variants/LinkList/Default"
SharedFields:
- ID: "19b597d3-2edd-4ae2-aefe-4a94c7f10e31"
  Hint: __Source Item
  Value: "sitecore://master/{F970277B-80F7-41D8-A12F-8BDBE91EA5C3}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "bf17f1f5-25d5-4668-b0e0-1f5b0bb83139"
Languages:
- Language: en
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "2d57dbf1-516a-403c-8df1-90c45333e6ed"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{F970277B-80F7-41D8-A12F-8BDBE91EA5C3}?lang=en&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220242Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c57414d0-c1fa-4ab0-a123-b5dc32b81fff"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220311Z
- Language: "es-ES"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "da2b568d-db26-4b00-b8c3-5b1e1043adfb"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{F970277B-80F7-41D8-A12F-8BDBE91EA5C3}?lang=es-ES&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220407Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7c148b66-12e9-404c-8455-eab11806efff"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220407Z
- Language: "fr-CA"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "4fb88b6f-b0cb-4b91-80c8-05f7de355bd7"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{F970277B-80F7-41D8-A12F-8BDBE91EA5C3}?lang=fr-CA&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220542Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7522c3a3-036b-4360-a414-566c13a5a934"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220542Z
- Language: "fr-FR"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "f4798142-4096-4e03-9da5-f0fa80f6046b"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{F970277B-80F7-41D8-A12F-8BDBE91EA5C3}?lang=fr-FR&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220439Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "405b692d-0fe7-4fa7-8476-e48b70ec0b56"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220439Z
