---
ID: "500dc2c2-aa93-4b06-862f-47ba6d3c6def"
Parent: "3c358fed-92ea-4d7b-bdd5-e220f4492af4"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/industry-verticals/littelfuse/Presentation/Headless Variants/Title/Default"
SharedFields:
- ID: "19b597d3-2edd-4ae2-aefe-4a94c7f10e31"
  Hint: __Source Item
  Value: "sitecore://master/{17437A73-D072-4574-8A49-360932DA0893}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "9f563b4f-be07-4ac8-a910-9864ab6b9bb2"
Languages:
- Language: en
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "bb1b47b6-cc34-4e6d-892e-d090a39635fc"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{17437A73-D072-4574-8A49-360932DA0893}?lang=en&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220259Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b6977698-5bce-4623-9067-14076f52e05a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220333Z
- Language: "es-ES"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "edf46169-a9d4-4a39-bc96-f0078cf90ce0"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{17437A73-D072-4574-8A49-360932DA0893}?lang=es-ES&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220422Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4dbccb16-f8fa-47f9-9080-f803a8c9e8c3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220422Z
- Language: "fr-CA"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "ac5019a6-ec5e-4ae4-bb73-3e811d3268ff"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{17437A73-D072-4574-8A49-360932DA0893}?lang=fr-CA&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220610Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7156d20a-b902-4d0a-8179-463b3903da7f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220610Z
- Language: "fr-FR"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "7f9ae825-0b94-43e8-bc99-2979f6e84a36"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{17437A73-D072-4574-8A49-360932DA0893}?lang=fr-FR&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220511Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e7072da8-b422-47cb-9bb3-d514f47fa1a3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220511Z
