---
ID: "fe4faad2-915e-438e-b2cf-996424864d9a"
Parent: "faef5433-7d70-4066-bf1e-91597d72b877"
Template: "1105b8f8-1e00-426b-bf1f-c840742d827b"
Path: "/sitecore/content/industry-verticals/littelfuse/Presentation/Page Designs/ProductPage"
SharedFields:
- ID: "19b597d3-2edd-4ae2-aefe-4a94c7f10e31"
  Hint: __Source Item
  Value: "sitecore://master/{1D3CCB5E-CA96-4974-9506-2FFC69CB5814}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "04462d71-2f00-412e-8ccf-be64ca611731"
Languages:
- Language: en
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "d01adf89-c0bc-4057-8113-484b69f7cb41"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{1D3CCB5E-CA96-4974-9506-2FFC69CB5814}?lang=en&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T215929Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "85de324d-3ea2-4609-bcd7-53d1c47c75db"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220123Z
- Language: "es-ES"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "6711c972-53e1-48b3-bd70-828cf6333492"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{1D3CCB5E-CA96-4974-9506-2FFC69CB5814}?lang=es-ES&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220230Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dc2b3478-e627-4bb5-b12e-b2ceb3509136"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220230Z
- Language: "fr-CA"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "afe59ec2-d897-4b64-9095-04cb3565b916"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{1D3CCB5E-CA96-4974-9506-2FFC69CB5814}?lang=fr-CA&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220446Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7ebbf448-9128-405d-afe9-90c698650d69"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220446Z
- Language: "fr-FR"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "27756b50-d4d5-40ba-b20d-76c1e109b61c"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{1D3CCB5E-CA96-4974-9506-2FFC69CB5814}?lang=fr-FR&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220342Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b4238227-76de-4ceb-bbd0-c6f5c0bad951"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220342Z
