---
ID: "225795ff-fe23-4da7-83b6-9da00872b4c6"
Parent: "faef5433-7d70-4066-bf1e-91597d72b877"
Template: "1105b8f8-1e00-426b-bf1f-c840742d827b"
Path: "/sitecore/content/industry-verticals/littelfuse/Presentation/Page Designs/ProductCategoryPage"
SharedFields:
- ID: "19b597d3-2edd-4ae2-aefe-4a94c7f10e31"
  Hint: __Source Item
  Value: "sitecore://master/{A0499ED8-EB40-4C56-A459-409E4DC028D3}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "4de6ad3c-0f13-44cb-ae53-65a9906c3143"
Languages:
- Language: en
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "2946fca4-11c8-4f88-9609-e20e4f825bdd"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{A0499ED8-EB40-4C56-A459-409E4DC028D3}?lang=en&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T215930Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dab38dc3-ebc3-4717-8900-acd1dd724dd9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220121Z
- Language: "es-ES"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "b68e58fc-24bb-49ce-be99-4186ecc3b0a7"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{A0499ED8-EB40-4C56-A459-409E4DC028D3}?lang=es-ES&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220226Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "70c80893-8298-4249-a3bc-8030ae685e8e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220226Z
- Language: "fr-CA"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "29dda613-e217-4a8c-b0a4-011d90952ca5"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{A0499ED8-EB40-4C56-A459-409E4DC028D3}?lang=fr-CA&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220429Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "189842e4-8f9d-49aa-9490-d84d680a92d0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220429Z
- Language: "fr-FR"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "beceaa50-4ea1-4870-bf1f-3e1195d5a52b"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{A0499ED8-EB40-4C56-A459-409E4DC028D3}?lang=fr-FR&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260315T220335Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2ae34e26-c572-4797-b464-bb26bba95123"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\megan.chavez@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260315T220335Z
